### PR TITLE
Update DisplayLink and Evdi

### PR DESCRIPTION
**Pull request by elguero**
This commit will allow us to create RPM based on:
  * DisplayLink Manager 5.1.26
  * evdi 1.6.0

issue #83

### CODE REVIEW

**Comment by elguero** [comment]
Until evdi 1.6.0 is released, the checks are going to fail...

**Comment by ssaavedra** [comment]
Looks good to merge.

However, if it's alright, I'll wait for @displaylink-dkurek to actually tag the evdi repo and not break this build. It seems that the release of the Displaylink binary version was more important than actually packing the open-source software it's dependent on.

Unfortunately, that attitude will need to change if the spirit is to ever try to mainline the evdi module.

Please, ping me back here if I don't see the tag on evdi so that this gets merged.

**Comment by displaylink-dkurek** [comment]
Evdi v1.6.0 was tagged :)

**Comment by ssaavedra** [comment]
Thanks for the ping, just re-run Travis and merged.

Thank you for the contribution, @elguero!

**Pull request merged**
