### PR TITLE
Added RHEL8.1+ support

### PR DESCRIPTION
**Pull request by sbluhm**
1. SPEC file enhanced to patch evdi for EL8.1 and 8.2. Use flag --with el81 to build the el8 package.
2. Makefile modified to also build an .el8 package for EL 8.1/8.2

### CODE REVIEW

**Comment by elguero** [comment]
Thank you for the contribution.

As I mentioned in the issue, I feel we should wait until the EVDI accepts the change on their end.  We attempted to do our own custom patches while waiting on EVDI in the past and it caused many headaches for people as the target get moving and too much time needed to be dedicated to maintaining a custom patch for EVDI.

My suggestion would be to push getting your patches merged into the EVDI project and then we can look at if we need to make any adjustments to the RPM creation process.

**Comment by sbluhm** [comment]
This has now been merged to the displaylink devel branch. I will wait for a release and then check if anything needs to be done to the spec file.

**Comment by jacobleonwoffenden** [comment]
Hey - has there been any update on this?

**Comment by sbluhm** [comment]
As there has been no upstream release since, there can't be an update. If you want this fix, you can grab it from my repository in the meantime: https://github.com/sbluhm/displaylink-rpm
Or follow my instructions here: https://www.bluhm-de.com/content/os-tools/en/linux/install-lenovo-thinkpad-usb-3-0-dock-on-centos-8--displaylink-ad.html

**Comment by sbluhm** [comment]
Not actually sure. Been too long and I am out of this topic. So do feel free to close it if this is not wanted or required.

**Pull request closed without merging**
