### PR TITLE
Use github api to determine upstream versions

### PR DESCRIPTION
**Pull request by tartansandal**
Use the GitHub API to determine:
1. The latest released version of EVDI (including prereleases)
2. The date of the last commit to the devel branch (used for versioning rawhide builds)

Caveat: This can slow the build a bit depending on GitHub load and rate limiting.

### CODE REVIEW

**Comment by tartansandal** [comment]
There is a concern that the delay in querying GitHub may cause users to think the build has hung. I've seen it take up to 10s in bad circumstances. Need to figure out some way to show that GitHub is being queried during the build. I don't think we can d that inside a $(shell ...) construct. Recursive $(MAKE) might work, but could be confusing to future developers.

**Comment by ssaavedra** [comment]
Maybe it's good to make it optional, or maybe be able to cache it in a file e.g., `_versions` and a `_versions` target to provide the values. Then we can just grep/sed the values to the Makefile variables.

**Comment by tartansandal** [comment]
The motivation behind this PR was to get access to the date of the last commit on the `devel` branch so we can _version_ the `rawhide` builds sensibly and consistently.  Currently you can quickly end up with a stack of effectively identical rawhide RPMs with different versions. I definitely think we should tweak the build so that `devel` branch date check only happens when you do a rawhide build, but a I also think this should _not_ be optional for rawhide builds.

Doing the same thing for the main EVDI version was trivial once I'd figured out how to use the GitHub API for the above. This was mentioned somewhere else as being desirable, so I added the feature, although I'm not sure I see it as adding much benefit. It does make some things more automated, but the end user would still have to rebuild the RPM (from their git checkout) to detect the version change. I think it would be unusual for them to not do a `git fetch` to see if we had made any changes first. Also, we would probably know about new EVDI releases before most end users and bumping the versions in two files is really not that hard :-). Perhaps adding a Makefile target that developers could use to quickly check if upstream had bumped its versions would be a better way to go?

Caching is problematic -- when do we expire the cache? Few people (a part from this project's developers) would be running this more than once a day, so I don't think we get a significant benefit.  

This issue, as I see it, is more around getting `make` to provide user feedback during the process: simply printing "Checking upstream versions ..." so the end user does not think it has hung. I'm sure there is some Makefile magic to get that to happen. I  may get a chance to work some more on this later this week.

**Comment by ssaavedra** [comment]
The changes look OK to me, but could you please rebase your branch on top of the current master so that we go linearly and don't go back to previous versions?
(I know it's my fault for taking so long to review this PR)

**Comment by tartansandal** [comment]
No problems ;-)

With the rebase, do you want me to squash it into a single commit?

( I have to confess, although I'm quite comfortable rebasing locally, I'm a
little nervous about rebasing with GitHub, since mistakes can be hard to
fix and I'm not 100% clear on what GitHub is doing with pull requests.
Normally I would merge the current master branch into the PR branch,
resolve any conflicts there, then merge the PR from Github ).

**Comment by ssaavedra** [comment]
If you're ok with squashing it to a single commit we can do that from the GitHub interface when merging, and you can merge master into the PR branch if you'd rather do it that way.

But for clarification, (from my experience with GitHub) PRs track your branch, so if you `push --force` your branch, you'll update your PR to match that. That is, your patch is still as if you were about to merge your PR branch onto the PR base.

Also, from some months ago, you can see the history of changesets you've uploaded to a PR, so that you can review your changes in time (similarly to how Gerrit works, except in Gerrit changesets must have a single commit).

**Comment by tartansandal** [comment]
Ah thanks for the heads up about how GitHub handles PRs. In future, I'll probably do a local rebase and squash, then `push --force`. Unfortunately, I seem to have already merged in master with my last push, so I'll give merge and squash via the interface a try.

**Pull request merged**
