### PR TITLE
Adding Fedora 33 Target

### LINKED ISSUE #150: F33 build target
As of today, Fedora 33 has been officially released. An f33 build target should probably be added to CI.

### PR DESCRIPTION
**Pull request by elguero**
Adding Fedora 33 as a target for Travis to build.

Closes #150

### CODE REVIEW

**Comment by wernermaes** [comment]
I haven't upgraded to F33 yet, so I suppose I will have to delay this upgrade since I will end up with kernel 5.9 if I upgrade now.

**Comment by pkruesi** [comment]
Is there a problem with kernel 5.9? I use Fedora32 und saw that dkms cant build the module anymore since Fedora uses kernel kernel-5.9.8-100.fc32.x86_64.

**Comment by elguero** [comment]
@pkruesi  That is correct.  F32 has been updated to 5.9 as well I saw today.  As we have been saying on other issues, please see https://github.com/DisplayLink/evdi/pull/228.  We are waiting on DisplayLink to merge and release a new verson of evdi that works with 5.9.

**Comment by abucodonosor** [comment]
@elguero 

That is NOT correct. 

The real PR is https://github.com/DisplayLink/evdi/pull/227, which is merged already, https://github.com/DisplayLink/evdi/pull/228,
is the patch against 1.7 release.

**Comment by elguero** [comment]
@abucodonosor Hmm. I am not sure where I made a mistake. Sorry for any confusion.

Not sure what I am missing.  I believe that is what I pointed to.

The only working solution right now is DisplayLink driver version 5.3.1 and evdi 1.7.0.  Since that is the only combination that works, I referred to the backport of your patch for evdi 1.7.x that we are waiting to be merged and subsequently released.

**Comment by abucodonosor** [comment]
Well, the point is you don't need to wait, since the patch is merged, tested, and works on released tarball and master.

I don't see why you would wait for something to be released on a tag ( which doesn't even exist ) when is a matter of 2 lines added to the spec and have 1.7 working with a up2 5.9.x kernel.

**Comment by elguero** [comment]
Sure, people are free to do that if they need it.  That is why I keep referencing that patch for those who know how to apply a patch and build a new RPM.

This is a community driven project.  Whatever the community that uses this project decides is fine with me.  Hopefully others can help support having to keep up with the patches, if that is what the decision is to do.  Last time we tried this, the community requested not to do this.  I am just trying to be respectful of that wish from others.

Past experiences has taught me to not chase a moving target if you want less support requests and more time doing the stuff that pays the bills.

**Pull request merged**
