### PR TITLE
evdi devel branch support

### PR DESCRIPTION
**Pull request by tartansandal**
Add support for (optionally) building against the `devel` branch of the evdi library.

Also includes some Makefile cleanup.

### CODE REVIEW

**Comment by ssaavedra** [comment]
Sorry I didn't have time to review this before.

I like the new Makefile a lot.

But I'm a bit concerned on the versioning (calling it 1.5.0 blindly), because that would impede upgrading to actual 1.5.0 when that happens. Not sure what we should do then. Maybe our development version could be named $(VERSION).1.rawhide, what do you think?

Now, keeping in mind that these packages get built by Travis:

Instead of hard-coding `/tmp/evdi-devel` we could also make that a variable (for easier replacement of the repo, so that we can cache that in the Travis cache).

Besides, we should be able to use an env-var to enforce a certain branch/commit to be built on the evdi branch.

If it's feasible (not sure about that) the version of evdi could be grabbed from `git describe --tags`.

**Comment by tartansandal** [comment]
No worries mate. Glad you like the new Makefile. :-)

(Just as an aside, thank you so much for putting this project together -- I was close to throwing my new D3100 in the bin before I discovered it)

I was not particularly happy with the rawhide version hack either. The RPM version sorting algorithm is more complicated than most people think, so I just opted for something that would always win.

I've just checked with the fedora release version guidelines (https://fedoraproject.org/wiki/Packaging:Versioning) and I think the following format will work best:

	$(VERSION).$(RELEASE).rawhide.$(DATE)

where $(DATE) is the build date of the RPM in YYYYMMDD format. I believe this will make 

*    rawhide versions sort higher than mainline
*    newer rawhide builds to sort higher than older
*    new versions sort higher than rawhide

Let me know what you think and I'll adjust the Makefile and README

**Comment by tartansandal** [comment]
I agree that wrapping '/var/tmp/evdi-devel' in a variable that can be overridden from the environment is a good idea and easy to do. I'm less familiar with travis and have not idea how to make the cache stuff work though. 

On the flip side, we clone the evid devel branch with `--depth 1`, so it is actually quite small. Caching may only have a very small effect on the travis builds and the added complexity may be counter-productive.

**Comment by tartansandal** [comment]
Looking at the upstream evdi project and I'm thinking that tracking specific branches/commits may be a bit of a Pandora's box. The rawhide solution is really just an "if all else fails, try this" approach. 

It would be great if we had upstream managing a 'fedora' branch with all the bits from 'devel' that are required to get new kernels to compile, but without the experimental stuff from `devel`.

**Comment by ssaavedra** [comment]
Hi,

First of all, this is a community effort, so we should be thanking everyone, including first-time contributors such as yourself today for making this possible :)

About the rawhide versioning proposal you mention: great idea, I think that's spot on.

Second, no worries about Travis, but it may make it easier for me to change paths later on in the `.travis.yml` if for some reason I want to build somewhere near my home directory instead of at /tmp.

As for the branches/commits, I am not trying to say that we should add logic anyhow for that; but maybe instead of cloning `-b devel` we could clone `-b $(EVDI_DEVEL_BRANCH)` and have it set up as `EVDI_DEVEL_BRANCH ?= devel`, or clone `--depth=50` so that we can do something like `[[ -n "$(EVDI_DEVEL_HASH)" ]] && git checkout $(EVDI_DEVEL_HASH)` after the clone.

I am thinking on the release process: currently, we push a tag to this repo and that triggers Travis to build and push the built artifacts to the release page for the tag. If we pushed a tag with a specific name, such as, e.g., `1.2.3-dev-git+ee1c578` we could have the releases crafted in a way such that their name is still meaningful (and we can re-build "devel" in the future without disposing of the old tag). No worries about this part, I can take care of it, I just mention it so that you can know why I thought about that :)

That is orthogonal to the versioning scheme; I don't really care much whether the final RPM bears the git-hash of the evdi build as of now; once this is working and packages are live on Travis we can take care of better traceability.

Thanks for the effort you put on this.

**Comment by ssaavedra** [comment]
Anyway, if you can get the versioning scheme ready, I can probably prepare the releasing this weekend, and follow-up in another PR, so that we can start merging.

**Comment by ssaavedra** [comment]
Also, now that the other PR has been merged, please rebase your branch on top of current master to resolve the conflict on the Makefile.

**Comment by tartansandal** [comment]
Good Morning,

New rawhide versioning scheme implemented and checks pass :-)

Also added two new Makefile variables:

* EVDI_DEVEL_BRANCH (devel)
* EVDI_DEVEL_BASE_DIR (/var/tmp)

So you can now do stuff like:

    make EVDI_DEVEL_BASE_DIR=$HOME/tmp

This is a little bit clunky, but the approach was required to get the tarballs to unpack the same as upstream.

Enjoy!

**Pull request merged**
