### PR TITLE
Added more build dependencies

### PR DESCRIPTION
**Pull request by deajan**
On vanilla Fedora 29 Workstation, make is not installed by default.

### CODE REVIEW

**Comment by deajan** [comment]
Build failures seem to come from the displaylink download where ``` 
wget --post-data="fileId=1261&accept_submit=Accept" -O DisplayLink\ USB\ Graphics\ Software\ for\ Ubuntu\ 4.4.24.zip http://www.displaylink.com/downloads/file?id=1261``` does not work and downloads a html page.

**Comment by ssaavedra** [comment]
Thanks for spotting this!

Could you please rebase your changes on top of the current master? I've not ben actively monitoring this repo last month and I've just integrated some other changes which, unfortunately, break your patch from easily being merged.

**Comment by deajan** [comment]
Should be okay

**Comment by ssaavedra** [comment]
22335eed202822d0accec726c40d0a2bed77dd6b merges your changeset, since this PR's state was invalid again.

Thanks for your contribution!

**Pull request closed without merging**
